NumStages: 2 # Number of model investment planning stages
StageLengths: [6, 5] # Length of each model stage (years)
WACC: 0.00 # Weighted average cost of capital
ConvergenceTolerance: 0.01 # Relative optimality gap used for convergence
Myopic: 1 # 1 = myopic, 0 = dual dynamic programming
